[project]
name = "room-reservation"
version = "0.1.0"
description = "An app for reservating conference rooms"
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django (==5.1.5)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "uuid (>=1.30,<2.0)",
    "environ (>=1.0,<2.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "django-redis (>=5.4.0,<6.0.0)",
    "djangorestframework (>=3.16.0,<4.0.0)",
    "django-cors-headers (>=4.7.0,<5.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.2.0"
black = "^25.1.0"
flake8 = "^7.2.0"
isort = "^6.0.1"
mypy = "^1.15.0"
django-stubs = {extras = ["compatible-mypy"], version = "^5.2.0"}

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
ignore_missing_imports = true
mypy_path = "./room_reservation"

[tool.django-stubs]
django_settings_module = "room_reservation.settings"

[tool.isort]
profile = "black"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_first_party = ["api"]
