# Generated by Django 5.1.7 on 2025-05-08 08:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_field_chr', models.CharField(max_length=100)),
                ('test_field_int', models.IntegerField(default=111)),
            ],
        ),
    ]
