# Generated by Django 5.1.5 on 2025-05-21 12:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address", models.CharField(verbose_name=50)),
                ("room_name", models.CharField(max_length=50)),
                ("human_capacity", models.IntegerField()),
            ],
        ),
    ]
