# Generated by Django 5.1.5 on 2025-05-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="human_capacity",
            field=models.IntegerField(default=10),
        ),
    ]
