# Generated by Django 5.1.5 on 2025-05-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_room_human_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="address",
            field=models.CharField(max_length=50),
        ),
    ]
