# Generated by Django 5.1.5 on 2025-05-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_alter_room_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="human_capacity",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
