# Generated by Django 5.1.5 on 2025-05-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
        ("rooms", "0003_alter_room_address"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("room", "start", "end")},
        ),
    ]
