# Generated by Django 5.1.5 on 2025-06-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_amenities"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
