# Generated by Django 5.1.5 on 2025-06-10 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_reservation_is_cancelled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={"ordering": ["-attends"]},
        ),
        migrations.AlterField(
            model_name="participant",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="api.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="api.room",
            ),
        ),
    ]
