# Generated by Django 5.1.5 on 2025-06-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_participant_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenities",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["start"]},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["room_name"]},
        ),
        migrations.AddField(
            model_name="reservation",
            name="recovery_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("room_name", "address")},
        ),
    ]
